services:
  nginx-gateway:
    build:
      context: ./nginx
    container_name: nginx-gateway
    ports:
      - "8087:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/lua:/usr/local/openresty/lualib/custom:ro
      - ./nginx/logs:/var/log/nginx
    environment:
      - AUTH_SERVICE_URL=http://auth-service:8000/api/auth/check-token
      - AUTH_CACHE_TTL=300
    depends_on:
      - auth_service
      - main_service
    networks:
      - laravel_net

  auth_service:
    build:
      context: ./auth_service
      dockerfile: Dockerfile
    container_name: auth-service
    ports:
      - "8001:8000"
    volumes:
      - ./auth_service:/var/www
    depends_on:
      - auth_postgres
    env_file:
      - ./auth_service/.env
    environment:
      - DB_HOST=auth_postgres
      - DB_DATABASE=packages-management
    networks:
      - laravel_net

  main_service:
    build:
      context: ./main_service
      dockerfile: Dockerfile
    container_name: main-service
    ports:
      - "6500:6500"
    volumes:
      - ./main_service:/var/www
    environment:
      - DB_HOST=auth_postgres
      - DB_DATABASE=packages-management
      - FAKE_AUTH_ENABLED=true
    networks:
      - laravel_net


  auth_postgres:
    image: postgres:15
    container_name: pkg-manage-auth-db
    environment:
      POSTGRES_DB: packages-management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - auth_pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - laravel_net

volumes:
  auth_pgdata:

networks:
  laravel_net:
    driver: bridge